### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by haifenghuang** [xmh0511/string-plus-plus#1]
Belwo code:

```c++
 enum  class reg_mode:std::size_t
 {
        signle,
        global
 };
```
`signle` should be `single`?

**Comment by xmh0511** [comment]
> Belwo code:
> 
> ```c++
>  enum  class reg_mode:std::size_t
>  {
>         signle,
>         global
>  };
> ```
> 
> `signle` should be `single`?

Yes, it should be `single`. Thanks.
